using MedSave.DTOs.HealthcareProviders;
using MedSave.Services.HealthcareProviders;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MedSave.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class HealthcareProvidersController : ControllerBase
{
    private readonly IHealthcareProvidersService _healthcareProvidersService;

    public HealthcareProvidersController(IHealthcareProvidersService healthcareProvidersService)
    {
        _healthcareProvidersService = healthcareProvidersService;
    }
    
    /// <summary>
    /// Returns all registered Healthcare Providers.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Healthcare Providers, without contact and provider type details.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns></returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var dtos = await _healthcareProvidersService.GetAllAsync();

            return Ok(new { items = dtos });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Healthcare Providers",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Healthcare Provider by ID.
    /// </summary>
    /// <param name="id">Healthcare Provider ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific Healthcare Provider with details about its provider type and address.
    ///
    /// Possible status codes:
    ///
    /// - 200 OK: Healthcare Provider found and returned in the response body
    /// - 404 Not Found: no healthcare provider with the provided ID was found
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource <see cref="HealthcareProvidersDTO"/></returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var dto = await _healthcareProvidersService.GetByIdAsync(id);

            return Ok(dto);
        }
        catch (HealthcareProvidersService.NotFoundException ex)
        {
            return StatusCode(404, ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Healthcare Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Healthcare Provider in the database.
    /// </summary>
    /// <param name="dto">Data of the Healthcare Provider to be created.</param>
    /// <remarks>
    /// Endpoint that creates a Healthcare Provider, requiring its provider type and address data.
    ///
    /// Provider Type Id existents: 1 to 15 
    ///
    /// Automatically Generated Fields:
    /// - <c>healthcareProviderId</c>: generated by the database (IDENTITY)
    /// - <c>addressIdStock</c>: generated by the database (IDENTITY)
    ///
    /// Expected body (JSON) - only the fields the client needs to send:
    /// <code>
    /// {
    ///     "healthcareProvidersDto": {
    ///         "providerName": "string",
    ///         "healthcareProviderName": "string",
    ///         "providerTypeId": 1 - 15
    ///     },
    ///     "addressStockDto": {
    ///         "complement": "string",
    ///         "numberStock": 0,
    ///         "addressDescription": "string",
    ///         "cep": 12345678,
    ///         "neighId": 1
    ///     }
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: healthcare provider registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: unique information already registered
    /// - 500 Internal Server Error: unexpected error while registering the healthcare provider
    /// </remarks>
    /// <returns></returns>
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddHealthcareProviders([FromBody] CreateHealthcareProviderRequest createHealthcareProviderRequest)
    {
        try
        {
            var created = await _healthcareProvidersService.AddAsync(createHealthcareProviderRequest);
    
            return CreatedAtAction(nameof(GetById), new { id = created.HealthcareProviderId }, created);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(new { message = "Invalid request body." });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the Healthcare Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing healthcare provider.
    /// </summary>
    /// <param name="id">healthcare provider ID.</param>
    /// <remarks>
    /// Endpoint that updates the registration information of a healthcare provider stored in the database.
    /// It does not update address information.
    ///
    /// The healthcare provider ID is only required in the specified route parameter.
    /// If the same information is found in the request body, the value present in the request body will be ignored.
    ///
    /// <code>
    /// {
    ///     "providerName": "string",
    ///     "healthcareProviderName": "string",
    ///     "providerTypeId": 1 - 15
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: healthcare provider updated successfully
    /// - 404 Not Found: no healthcare provider with the provided ID was found
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 500 Internal Server Error: unexpected error while updating the healthcare provider
    /// </remarks>
    /// <param name="ID"></param>
    /// <param name="dto"></param>
    /// <returns></returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateHealthcareProvider(long id, [FromBody] HealthcareProvidersDTO healthcareProviderDto)
    {
        try
        {
            await _healthcareProvidersService.UpdateAsync(id, healthcareProviderDto);

            return Ok(new {message = $"Healthcare Provider with {id} updated"});
        }
        catch (HealthcareProvidersService.NotFoundException ex)
        {
            return NotFound(new { message = $"Healthcare Provider with id {id} not found" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(new { message = "Invalid request body." });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = $"Internal error when updating the Healthcare Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes a Healthcare Provider by ID.
    /// </summary>
    /// <param name="id">Healthcare Provider ID.</param>
    /// <remarks>
    /// Endpoint used to delete a Healthcare Provider registration from the database.
    ///
    /// Possible status codes:
    /// - 200 OK: healthcare provider deleted successfully
    /// - 404 Not Found: no healthcare provider with the provided ID was found
    /// - 500 Internal Server Error: unexpected error while deleting the healthcare provider
    /// </remarks>
    /// <returns></returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteHealthcareProvider(long id)
    {
        try
        {
            await _healthcareProvidersService.DeleteAsync(id);

            return Ok(new { message = $"Healthcare Provider with {id} deleted" });
        }
        catch (HealthcareProvidersService.NotFoundException ex)
        {
            return NotFound(new { message = $"Healthcare Provider with {id} not found" });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = $"Internal error when deleting the Healthcare Provider",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches healthcare providers with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="providerName">Healthcare provider provider name for optional filtering.</param>
    /// <param name="healthcareProviderName">Healthcare provider name for optional filtering.</param>
    /// <param name="providerTypeId">Healthcare provider type ID for optional filtering.</param>
    /// <param name="addressIdStock">Healthcare provider address ID for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>healthcareProviderId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns the Healthcare provider matching the search criteria, without address details.
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of manufacturers with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Search(
        [FromQuery] string? providerName,
        [FromQuery] string? healthcareProviderName,
        [FromQuery] long? providerTypeId,
        [FromQuery] long? addressIdStock,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "healthcareProviderId",
        [FromQuery] string sortDir = "asc"
        )
    {
        try
        {
            var result = await _healthcareProvidersService.SearchAsync(providerName, healthcareProviderName, providerTypeId, addressIdStock, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }

        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the manufacturer",
                details = ex.Message
            });
        }
    }
}