using MedSave.DTOs;
using MedSave.DTOs.Manufacturer;
using MedSave.Repositories;
using MedSave.Services.Manufacturer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MedSave.Controllers;

[ApiController]
[Route("api/[controller]")]
[Authorize]
public class ManufacturerController : ControllerBase
{
    private readonly IManufacturerService _manufacturerService;

    public ManufacturerController(IManufacturerService manufacturerService)
    {
        _manufacturerService = manufacturerService;
    }
    
    /// <summary>
    /// Returns all registered Manufacturers.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of manufacturers, without contact and address details.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 404 Not Found: no manufacturers found
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns></returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var dtos = await _manufacturerService.GetAllAsync();

            return Ok(new { items = dtos });
        }
        catch (ManufacturerRepository.NotFoundException ex)
        {
            return NotFound(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the manufacturers",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific Manufacturer by ID.
    /// </summary>
    /// <param name="id">Manufacturer ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific manufacturer with details about its contact and address.
    ///
    /// Possible status codes:
    ///
    /// - 200 OK: manufacturer found and returned in the response body
    /// - 404 Not Found: no manufacturer with the provided ID was found
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource <see cref="ManufacturerDTO"/></returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var dto = await _manufacturerService.GetByIdAsync(id);

            return Ok(dto);
        }

        catch (ManufacturerRepository.NotFoundException ex)
        {
            return StatusCode(404, ex.Message);
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the manufacturer",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Registers a new Manufacturer in the database.
    /// </summary>
    /// <param name="dto">Data of the Manufacturer to be created.</param>
    /// <remarks>
    /// Endpoint that creates a manufacturer, requiring its contact and address data.
    ///
    /// Automatically Generated Fields:
    /// - <c>manufacId</c>: generated by the database (IDENTITY)
    /// - <c>contactManuId</c>: generated by the database (IDENTITY)
    /// - <c>addressIdManufacturer</c>: generated by the database (IDENTITY)
    ///
    /// Expected body (JSON) - only the fields the client needs to send:
    /// <code>
    ///    {
    ///        "manufacturerDto": {
    ///            "nameManu": "string",
    ///            "cnpj": 12345678912345
    ///        },
    ///        "contactManufacturerDto": {
    ///            "emailManu": "string",
    ///            "phoneNumberManu": 11912345678
    ///        },
    ///        "addressManufacturerDto": {
    ///            "complement": "N/A",
    ///            "numberManu": 123,
    ///            "addressDescription": "Rua da Silva",
    ///            "cep": 12345678,
    ///            "neighId": 1
    ///        }
    ///    }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: manufacturer registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: unique information already registered
    /// - 500 Internal Server Error: unexpected error while registering the manufacturer
    /// </remarks>
    /// <returns></returns>
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status409Conflict)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddManufacturer([FromBody] CreateManufacturerRequest req)
    {
        try
        {
            var created = await _manufacturerService.AddAsync(req.ManufacturerDto, req.AddressManufacturerDto, req.ContactManufacturerDto);
            
            return CreatedAtAction(nameof(GetById), new {id = created.ManufacId}, created);
        }

        catch (ArgumentNullException ex)
        {
            return BadRequest(new { message = "Invalid request body." });
        }

        catch (ManufacturerService.ConflictException ex)
        {
            return StatusCode(409, new { message = "CNPJ already registered." });
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the manufacturer",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing Manufacturer.
    /// </summary>
    /// <param name="id">Manufacturer ID.</param>
    /// <remarks>
    /// Endpoint that updates the registration information of a manufacturer stored in the database.
    /// It does not update contact and address information.
    ///
    /// The manufacturer ID is only required in the specified route parameter.
    /// If the same information is found in the request body, the value present in the request body will be ignored.
    ///
    /// <code>
    /// {
    ///     "nameManu": "string",
    ///     "cnpj": 0,
    ///     "contactManuId": 0,
    ///     "addressIdManufacturer": 0
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: manufacturer updated successfully
    /// - 404 Not Found: no manufacturer with the provided ID was found
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 500 Internal Server Error: unexpected error while updating the manufacturer
    /// </remarks>
    /// <param name="ID"></param>
    /// <param name="dto"></param>
    /// <returns></returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateManufacturer(long id, [FromBody] ManufacturerDTO dto)
    {
        try
        {
            dto.ManufacId = id;

            await _manufacturerService.UpdateAsync(id, dto);
            return StatusCode(200, new { message = $"Manufacturer with id {id} updated" });
        }

        catch (ManufacturerService.NotFoundException ex)
        {
            return NotFound(new { message = $"Manufacturer with Id {id} not found" });
        }
        
        catch (ArgumentNullException ex)
        {
            return BadRequest(ex.Message);
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when adding the manufacturer",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Deletes a Manufacturer by ID.
    /// </summary>
    /// <param name="id">Manufacturer ID.</param>
    /// <remarks>
    /// Endpoint used to delete a manufacturer registration from the database.
    ///
    /// Possible status codes:
    /// - 200 OK: manufacturer deleted successfully
    /// - 404 Not Found: no manufacturer with the provided ID was found
    /// - 500 Internal Server Error: unexpected error while deleting the manufacturer
    /// </remarks>
    /// <returns></returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteManufacturer(long id)
    {
        try
        {
            await _manufacturerService.DeleteAsync(id);

            return Ok(new { message = $"Manufacturer with Id {id} deleted" });
        }
        
        catch (ManufacturerService.NotFoundException ex)
        {
            return NotFound(new { message = $"Manufacturer with Id {id} not found" });
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when deleting the manufacturer",
                details = ex.Message
            });
        }
    }

    /// <summary>
    /// Searches manufacturers with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="cnpj">Manufacturer CNPJ for optional filtering.</param>
    /// <param name="contactManuId">Manufacturer contact ID for optional filtering.</param>
    /// <param name="addressIdManufacturer">Manufacturer address ID for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>manufacId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns the manufacturers matching the search criteria, without contact and address details.
    /// 
    /// Request example:
    /// <code>
    /// GET /api/Manufacturer/search?cnpj=123456789&amp;page=1&amp;pageSize=10&amp;sortBy=manufacId&amp;sortDir=asc
    /// </code>
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of manufacturers with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Search(
        [FromQuery] int? cnpj,
        [FromQuery] long? contactManuId,
        [FromQuery] long? addressIdManufacturer,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "manufacId",
        [FromQuery] string sortDir = "asc"
    )
    {
        try
        {
            var result = await _manufacturerService.SearchAsync(cnpj, contactManuId, addressIdManufacturer, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }

        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the manufacturer",
                details = ex.Message
            });
        }
    }
}