using MedSave.DTOs.UsersSys;
using MedSave.Services.UsersSys;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MedSave.Controllers;

[ApiController]
[Authorize]
[Route("api/[controller]")]
public class UsersSysController : ControllerBase
{
    private readonly IUsersSysService _usersSysService;

    public UsersSysController(IUsersSysService usersSysService)
    {
        _usersSysService = usersSysService;
    }

    /// <summary>
    /// Returns all registered Users.
    /// </summary>
    /// <remarks>
    /// Non-paginated endpoint. Returns the complete collection of Users, without contact.
    ///
    /// Possible status codes:
    /// - 200 OK: collection returned successfully
    /// - 500 Internal Server Error: unexpected error while retrieving data
    /// </remarks>
    /// <returns></returns>
    [HttpGet]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetAll()
    {
        try
        {
            var dtos = await _usersSysService.GetAllAsync();

            return Ok(new { items = dtos });
        }
        catch (Exception e)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the Users",
                details = e.Message
            });
        }
    }

    /// <summary>
    /// Gets a specific User by ID.
    /// </summary>
    /// <param name="id">User ID.</param>
    /// <remarks>
    /// Endpoint that returns a specific User with details about its contact.
    ///
    /// Possible status codes:
    ///
    /// - 200 OK: User found and returned in the response body
    /// - 404 Not Found: no User with the provided ID was found
    /// - 500 Internal Server Error: unexpected server error
    /// </remarks>
    /// <returns>Resource <see cref="UsersSysDTO"/></returns>
    [HttpGet("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> GetById(long id)
    {
        try
        {
            var dto = await _usersSysService.GetByIdAsync(id);

            return Ok(dto);
        }
        catch (UsersSysService.NotFoundException ex)
        {
            return StatusCode(404, ex.Message);
        }
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the user",
                details = ex.Message
            });
        }
    }

    // {
    //     "contactUserDto": {
    //         "emailUser": "testedasilva@gmail.com",
    //         "phoneNumberUser": 11912345678
    //     },
    //     "usersSysDto": {
    //         "email": "testedasilva@gmail.com",
    //         "nameUser": "John usuario",
    //         "passwordUser": "pedrogay123",
    //         "roleUserId": 1,
    //         "profUserId": 1
    //     }
    // }
    /// <summary>
    /// Registers a new User in the database.
    /// </summary>
    /// <param name="dto">Data of the User to be created.</param>
    /// <remarks>
    /// Endpoint that creates a User, requiring its contact.
    ///
    /// Role User Id existents: 1 to 15
    /// Prof User Id existents: 1 to 15
    ///
    /// Automatically Generated Fields:
    /// - <c>userId</c>: generated by the database (IDENTITY)
    /// - <c>contactUserId</c>: generated by the database (IDENTITY)
    ///
    /// Expected body (JSON) - only the fields the client needs to send:
    /// <code>
    /// {
    ///     "contactUserDto": {
    ///         "emailUser": "string",
    ///         "phoneNumberUser": 123
    ///     },
    ///     "usersSysDto": {
    ///         "email": "string",
    ///         "nameUser": "string",
    ///         "passwordUser": "string",
    ///         "roleUserId": 1,
    ///         "profUserId": 1
    ///     }
    /// }
    /// </code>
    ///
    /// Possible status codes:
    /// - 201 Created: User registered successfully
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 409 Conflict: unique information already registered
    /// - 500 Internal Server Error: unexpected error while registering the User
    /// </remarks>
    /// <returns></returns>
    [AllowAnonymous]
    [HttpPost]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> AddUsersSys([FromBody] CreateUserRequest createUserRequest)
    {
        try
        {
            var created = await _usersSysService.AddAsync(createUserRequest);

            return CreatedAtAction(nameof(GetById), new { id = created.UserId }, created);
        }
        catch (UsersSysService.ConflictException ex)
        {
            return Conflict(ex.Message);
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(new { message = "Invalid request body." });
        }
        catch (Exception e)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching for the user",
                details = e.Message
            });
        }
    }

    /// <summary>
    /// Updates the information of an existing user.
    /// </summary>
    /// <param name="id">user ID.</param>
    /// <remarks>
    /// Endpoint that updates the registration information of a user stored in the database.
    /// It does not update contact information.
    ///
    /// The user ID is only required in the specified route parameter.
    /// If the same information is found in the request body, the value present in the request body will be ignored.
    ///
    /// {
    ///     "nameUser": "string",
    ///     "email": "string",
    ///     "passwordUser": "string",
    ///     "roleUserId": 0,
    ///     "profUserId": 0,
    /// }
    ///
    /// Possible status codes:
    /// - 200 OK: user updated successfully
    /// - 404 Not Found: no user with the provided ID was found
    /// - 400 Bad Request: invalid or inconsistent payload
    /// - 500 Internal Server Error: unexpected error while updating the user
    /// </remarks>
    /// <param name="ID"></param>
    /// <param name="dto"></param>
    /// <returns></returns>
    [HttpPut("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> UpdateUser(long id, [FromBody] UsersSysDTO dto)
    {
        try
        {
            await _usersSysService.UpdateAsync(id, dto);

            return Ok(new { message = $"User with id {id} updated" });
        }
        catch (UsersSysService.NotFoundException ex)
        {
            return NotFound(new { message = $"User with Id {id} not found" });
        }
        catch (ArgumentNullException ex)
        {
            return BadRequest(new { message = "Invalid request body." });
        }
        catch (Exception e)
        {
            return StatusCode(500, new
            {
                message = "Internal error when updating the manufacturer",
                details = e.Message
            });
        }
    }

    /// <summary>
    /// Deletes a user by ID.
    /// </summary>
    /// <param name="id">user ID.</param>
    /// <remarks>
    /// Endpoint used to delete a user registration from the database.
    ///
    /// Possible status codes:
    /// - 200 OK: user deleted successfully
    /// - 404 Not Found: no user with the provided ID was found
    /// - 500 Internal Server Error: unexpected error while deleting the user
    /// </remarks>
    /// <returns></returns>
    [HttpDelete("{id:long}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> DeleteUser(long id)
    {
        try
        {
            await _usersSysService.DeleteAsync(id);

            return Ok(new { message = $"User with id {id} deleted" });
        }
        catch (UsersSysService.NotFoundException ex)
        {
            return NotFound(new { message = $"User with id {id} not found" });
        }
        catch (Exception e)
        {
            return StatusCode(500, new
            {
                message = $"Internal error when deleting the user",
                details = e.Message
            });
        }
    }

    /// <summary>
    /// Searches user with optional filters, pagination, and sorting.
    /// </summary>
    /// <param name="email">User email for optional filtering.</param>
    /// <param name="roleUserId">Role User ID for optional filtering.</param>
    /// <param name="profUserId">Profile User ID for optional filtering.</param>
    /// <param name="page">Page number. Default: 1, minimum: 1.</param>
    /// <param name="pageSize">Page size. Default: 10, maximum according to the application rule.</param>
    /// <param name="sortBy">Sorting field. Default: <c>healthcareProviderId</c>.</param>
    /// <param name="sortDir">Sorting direction: <c>asc</c> or <c>desc</c>.</param>
    /// <remarks>
    /// Returns the User matching the search criteria, without contact details.
    ///
    /// Possible status codes:
    /// - 200 OK: results returned successfully. The list may be empty
    /// - 400 Bad Request: invalid filter, pagination, or sorting parameters
    /// - 500 Internal Server Error: unexpected error while performing the search
    /// </remarks>
    /// <returns>Paginated collection of manufacturers with pagination information.</returns>
    [HttpGet("search")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    [ProducesResponseType(StatusCodes.Status401Unauthorized)]
    [ProducesResponseType(StatusCodes.Status500InternalServerError)]
    public async Task<IActionResult> Search(
        [FromQuery] string? nameUser,
        [FromQuery] string? email,
        [FromQuery] long? roleUserId,
        [FromQuery] long? profUserId,
        [FromQuery] int page = 1,
        [FromQuery] int pageSize = 10,
        [FromQuery] string sortBy = "userId",
        [FromQuery] string sortDir = "asc")
    {
        try
        {
            var result = await _usersSysService.SearchAsync(nameUser, email, roleUserId, profUserId, page, pageSize, sortBy, sortDir);

            return Ok(new { Items = result.Items, PageInfo = result.PageInfo });
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        
        catch (Exception ex)
        {
            return StatusCode(500, new
            {
                message = "Internal error when searching the manufacturer",
                details = ex.Message
            });
        }
    }
}